version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1

  web:
    build: .
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .samplerubyonrails.env
    environment:
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: password1
      RAILS_ENV: test
